"""Add contact column to doctors table

Revision ID: 841bc240b16d
Revises: 
Create Date: 2025-06-26 09:45:18.597969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841bc240b16d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
